
export const FETCH_ESTABLISHMENTS_START = 'FETCH_ESTABLISHMENTS_START';
export const FETCH_ESTABLISHMENTS_SUCCESS = 'FETCH_ESTABLISHMENTS_SUCCESS';
export const FETCH_ESTABLISHMENTS_FAIL = 'FETCH_ESTABLISHMENTS_FAIL';